### PR TITLE
increase 'timeout-keep-alive' from 5 to 60

### PR DESCRIPTION
**Pull request by StefanBogdan**

### CODE REVIEW

**Comment by bobvanluijt** [comment]
@antas-marcin or @etiennedi – can you take a look at this please?

**Comment by etiennedi** [comment]
I need some context on what this does and why, please. Thanks.

**Comment by bobvanluijt** [comment]
@byronvoorbach – can you help with this in @StefanBogdan's absence?

**Comment by StefanBogdan** [comment]
This increases the `Keep Alive` time span for the Connections. Docs in [here](https://www.uvicorn.org/settings/#timeouts).

I have noticed a lot of `connection reset by peer` errors from Weaviate (returned per item by batch creation), and nothing in Weaviate logs. If you think this is not needed please close this PR, without merging.

**Comment by etiennedi** [comment]
Thanks, that's helpful. If this solved a problem, I see no reason why not to merge it.

The reason I was initially confused is that - based on my understanding of TCP - keep-alive would only be needed to keep an idle connection open. So while an HTTP request is still open, keep alive should not play a role. It should only be a performance boost for reuse.

But if you're sure that this fixes the problem, I'm happy to merge this. I don't think it would hurt.

**Comment by antas-marcin** [comment]
@StefanBogdan do you think that this setting should be also applied to all other our inference containers?

**Review by antas-marcin — APPROVED** [review]

**Comment by StefanBogdan** [comment]
This does not add any value, closing it.

**Pull request closed without merging**
